import type { RouteRecordRaw } from 'vue-router';

const placeholder = {
  component: () => import('pages/shared/FeaturePlaceholderPage.vue'),
};

const routes: RouteRecordRaw[] = [
  {
    path: '/login',
    component: () => import('pages/auth/LoginPage.vue'),
  },
  {
    path: '/',
    component: () => import('layouts/MainLayout.vue'),
    children: [
      { path: '', name: 'dashboard', component: () => import('pages/dashboard/DashboardPage.vue') },
      {
        path: '/admin/condominiums',
        alias: ['/admin/condominios'],
        name: 'adminCondominiums',
        component: () => import('pages/condominiums/CondominiumsPage.vue'),
      },
      {
        path: '/admin/houses',
        alias: ['/admin/casas'],
        name: 'adminHouses',
        component: () => import('pages/houses/AdminHousesPage.vue'),
      },
      {
        path: '/admin/casas/duenos/nuevo',
        name: 'createHouseOwner',
        component: () => import('pages/houses/CreateHouseOwnerPage.vue'),
      },
      {
        path: '/admin/residents',
        alias: ['/admin/residentes'],
        name: 'residents',
        component: () => import('pages/residents/ResidentsPage.vue'),
      },
      {
        path: '/residentes/nuevo',
        name: 'createResident',
        component: () => import('pages/residents/CreateResidentPage.vue'),
      },
      {
        path: '/residentes/:id/editar',
        name: 'editResident',
        component: () => import('pages/residents/EditResidentPage.vue'),
      },
      {
        path: '/condominios/nuevo',
        name: 'createCondominium',
        component: () => import('pages/condominiums/CreateCondominiumPage.vue'),
      },
      {
        path: '/condominios/:id/editar',
        name: 'editCondominium',
        component: () => import('pages/condominiums/EditCondominiumPage.vue'),
      },
      {
        path: '/condominios/:id/administradores',
        name: 'condominiumAdministrators',
        component: () => import('pages/condominiums/CondominiumAdministratorsPage.vue'),
      },
      {
        path: '/condominios/:id/casas',
        name: 'condominiumHouses',
        component: () => import('pages/condominiums/CondominiumHousesPage.vue'),
      },
      {
        path: '/condominios/:id/directiva',
        name: 'condominiumDirective',
        component: () => import('pages/condominiums/CondominiumDirectivePage.vue'),
      },
      {
        path: '/admin/board',
        name: 'adminBoard',
        component: placeholder.component,
        props: {
          eyebrow: 'Administracion',
          title: 'Directivas',
          description: 'Selecciona un condominio para administrar su gestion y su directiva.',
          icon: 'groups',
          emptyMessage: 'Aqui se listaran los condominios para acceder a sus gestiones y directivas.',
          actionLabel: 'Ir a condominios',
          actionTo: '/admin/condominiums',
          actionIcon: 'apartment',
        },
      },
      {
        path: '/administradores',
        name: 'administrators',
        component: () => import('pages/administrators/AdministratorsPage.vue'),
      },
      {
        path: '/administradores/nuevo',
        name: 'createAdministrator',
        component: () => import('pages/administrators/CreateAdministratorPage.vue'),
      },
      {
        path: '/administradores/:id/editar',
        name: 'editAdministrator',
        component: () => import('pages/administrators/EditAdministratorPage.vue'),
      },
      { path: '/usuarios', name: 'users', component: () => import('pages/users/UsersPage.vue') },
      {
        path: '/usuarios/nuevo',
        name: 'createUser',
        component: () => import('pages/users/CreateUserPage.vue'),
      },
      {
        path: '/usuarios/:id/editar',
        name: 'editUser',
        component: () => import('pages/users/EditUserPage.vue'),
      },
      {
        path: '/reportes',
        name: 'reports',
        component: () => import('pages/reports/ReportsPage.vue'),
      },
      {
        path: '/admin/payments',
        name: 'payments',
        component: () => import('pages/payments/PaymentsPage.vue'),
      },
      {
        path: '/admin/payments/:id',
        name: 'paymentDetail',
        component: () => import('pages/payments/PaymentDetailPage.vue'),
      },
      {
        path: '/resident/statement',
        name: 'accountStatement',
        component: () => import('pages/payments/AccountStatementPage.vue'),
      },
      {
        path: '/resident/payments',
        name: 'residentPayments',
        component: placeholder.component,
        props: {
          eyebrow: 'Mi hogar',
          title: 'Mis pagos',
          description: 'Consulta el historial de pagos de tu casa.',
          icon: 'credit_card',
          emptyMessage: 'Este modulo mostrara el historial de pagos y comprobantes del residente.',
          actionLabel: 'Ver estado de cuenta',
          actionTo: '/resident/statement',
          actionIcon: 'description',
        },
      },
      {
        path: '/resident/advance-payments',
        name: 'residentAdvancePayments',
        component: placeholder.component,
        props: {
          eyebrow: 'Mi hogar',
          title: 'Adelantar alicuotas',
          description: 'Registra pagos adelantados a favor de la casa.',
          icon: 'calendar_month',
          emptyMessage: 'Este modulo permitira registrar adelantos de alicuotas.',
          actionLabel: 'Ver mis pagos',
          actionTo: '/resident/payments',
          actionIcon: 'credit_card',
        },
      },
      {
        path: '/resident/invitations',
        name: 'residentInvitations',
        component: placeholder.component,
        props: {
          eyebrow: 'Mi hogar',
          title: 'Invitaciones',
          description: 'Gestiona los accesos temporales de visitas e invitados.',
          icon: 'badge',
          emptyMessage: 'Este modulo permitira registrar invitaciones de acceso para la casa.',
          actionLabel: 'Volver al hogar',
          actionTo: '/resident/houses',
          actionIcon: 'home',
        },
      },
      {
        path: '/admin/fee-rates',
        alias: ['/admin/fee-charges', '/admin/alicuotas'],
        name: 'feeRates',
        component: placeholder.component,
        props: {
          eyebrow: 'Facturacion',
          title: 'Tarifas de alicuotas',
          description: 'Configura las tarifas base y ajustes por condominio.',
          icon: 'receipt_long',
          emptyMessage: 'Aqui se administraran las tarifas globales y por condominio.',
          actionLabel: 'Ir a alicuotas',
          actionTo: '/admin/fee-charges',
          actionIcon: 'receipt_long',
        },
      },
      {
        path: '/admin/payment-methods',
        name: 'paymentMethods',
        component: placeholder.component,
        props: {
          eyebrow: 'Facturacion',
          title: 'Metodos de pago',
          description: 'Gestiona las formas de pago disponibles para el sistema.',
          icon: 'account_balance_wallet',
          emptyMessage: 'Aqui se listaran los metodos de pago disponibles.',
          actionLabel: 'Ir a pagos',
          actionTo: '/admin/payments',
          actionIcon: 'payments',
        },
      },
      {
        path: '/admin/catalogs',
        name: 'catalogs',
        component: placeholder.component,
        props: {
          eyebrow: 'Configuracion',
          title: 'Catalogos',
          description: 'Administra los catalogos globales del sistema.',
          icon: 'account_tree',
          emptyMessage: 'Aqui se gestionaran los catalogos globales y sus items.',
          actionLabel: 'Ir a configuracion',
          actionTo: '/configuracion',
          actionIcon: 'settings',
        },
      },
      {
        path: '/admin/menus',
        name: 'menus',
        component: () => import('pages/menus/MenusPage.vue'),
      },
      {
        path: '/admin/roles',
        name: 'roles',
        component: () => import('pages/roles/RolesPage.vue'),
      },
      {
        path: '/admin/roles/:id/permisos',
        name: 'rolePermissions',
        component: () => import('pages/roles/RolePermissionsPage.vue'),
      },
      {
        path: '/admin/audit-logs',
        name: 'auditLogs',
        component: placeholder.component,
        props: {
          eyebrow: 'Configuracion',
          title: 'Auditoria',
          description: 'Consulta el historial de acciones del sistema.',
          icon: 'verified_user',
          emptyMessage: 'Aqui se mostrara la traza de auditoria y eventos de seguridad.',
          actionLabel: 'Ir a configuracion',
          actionTo: '/configuracion',
          actionIcon: 'settings',
        },
      },
      {
        path: '/perfil',
        name: 'profile',
        component: () => import('pages/profile/ProfilePage.vue'),
      },
      {
        path: '/admin/comunicados',
        name: 'communications',
        component: () => import('pages/communications/CommunicationsPage.vue'),
      },
      {
        path: '/admin/solicitudes-mantenimiento',
        name: 'maintenanceRequests',
        component: () => import('pages/maintenance/MaintenanceRequestsPage.vue'),
      },
      {
        path: '/reportes',
        name: 'reports',
        component: () => import('pages/reports/ReportsPage.vue'),
      },
      {
        path: '/resident/houses',
        name: 'residentHome',
        component: placeholder.component,
        props: {
          eyebrow: 'Mi hogar',
          title: 'Mi hogar',
          description: 'Panel principal del residente para su casa y sus accesos.',
          icon: 'home',
          emptyMessage: 'Este espacio mostrara el resumen de la casa del residente.',
          actionLabel: 'Ver estado de cuenta',
          actionTo: '/resident/statement',
          actionIcon: 'description',
        },
      },
      {
        path: '/configuracion',
        name: 'settings',
        component: () => import('pages/settings/SettingsPage.vue'),
      },
      {
        path: '/notificaciones',
        name: 'notifications',
        component: () => import('pages/notifications/NotificationsPage.vue'),
      },
      {
        path: '/notificaciones/:id',
        name: 'notificationDetail',
        component: () => import('pages/notifications/NotificationDetailPage.vue'),
      },
      {
        path: '/admin/casas/:id/historial',
        name: 'houseHistory',
        component: () => import('pages/houses/HouseHistoryPage.vue'),
      },
      {
        path: '/residentes/:id/historial',
        name: 'residentHistory',
        component: () => import('pages/residents/ResidentHistoryPage.vue'),
      },
    ],
  },
  {
    path: '/:catchAll(.*)*',
    component: () => import('pages/ErrorNotFound.vue'),
  },
];

export default routes;
